// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzQO9buPDwO0_9Yz_HgiCl7hO_-u0c5sM',
    appId: '1:650822100252:web:3ac70b4f65c953637386d9',
    messagingSenderId: '650822100252',
    projectId: 'chat-app-7e8e5',
    authDomain: 'chat-app-7e8e5.firebaseapp.com',
    storageBucket: 'chat-app-7e8e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeOgdsgWGiYPKsRnU0dxY_qiuh22fYpso',
    appId: '1:650822100252:android:a97c13c7e7c319e37386d9',
    messagingSenderId: '650822100252',
    projectId: 'chat-app-7e8e5',
    storageBucket: 'chat-app-7e8e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz-PaJj7lIi73eoHXWypoo6RfgepVmH_4',
    appId: '1:650822100252:ios:9b464dff57974e227386d9',
    messagingSenderId: '650822100252',
    projectId: 'chat-app-7e8e5',
    storageBucket: 'chat-app-7e8e5.firebasestorage.app',
    iosBundleId: 'com.example.realtimeChatApp',
  );
}
